const CC=[["#5a2e1e","#8a4b32"],["#b4233d","#e0576d"],["#d9962c","#f2c466"],["#e8c93a","#fff0a0"],["#4a2a3a","#7a3a52"],["#f0a020","#ffd061"]];
const PC={"110":["New Delhi","Delhi"],"400":["Mumbai","Maharashtra"],"560":["Bengaluru","Karnataka"],"700":["Kolkata","West Bengal"],"600":["Chennai","Tamil Nadu"],"500":["Hyderabad","Telangana"],"411":["Pune","Maharashtra"],"380":["Ahmedabad","Gujarat"],"302":["Jaipur","Rajasthan"],"226":["Lucknow","Uttar Pradesh"],"462":["Bhopal","Madhya Pradesh"],"452":["Indore","Madhya Pradesh"],"482":["Jabalpur","Madhya Pradesh"],"440":["Nagpur","Maharashtra"],"395":["Surat","Gujarat"],"800":["Patna","Bihar"],"160":["Chandigarh","Chandigarh"],"141":["Ludhiana","Punjab"],"282":["Agra","Uttar Pradesh"],"221":["Varanasi","Uttar Pradesh"],"492":["Raipur","Chhattisgarh"],"834":["Ranchi","Jharkhand"],"751":["Bhubaneswar","Odisha"],"682":["Kochi","Kerala"],"695":["Thiruvananthapuram","Kerala"],"122":["Gurugram","Haryana"],"121":["Faridabad","Haryana"],"422":["Nashik","Maharashtra"],"431":["Aurangabad","Maharashtra"],"390":["Vadodara","Gujarat"],"360":["Rajkot","Gujarat"],"313":["Udaipur","Rajasthan"],"342":["Jodhpur","Rajasthan"],"324":["Kota","Rajasthan"],"474":["Gwalior","Madhya Pradesh"],"248":["Dehradun","Uttarakhand"],"208":["Kanpur","Uttar Pradesh"],"211":["Prayagraj","Uttar Pradesh"],"250":["Meerut","Uttar Pradesh"],"781":["Guwahati","Assam"],"641":["Coimbatore","Tamil Nadu"],"625":["Madurai","Tamil Nadu"],"530":["Visakhapatnam","Andhra Pradesh"],"520":["Vijayawada","Andhra Pradesh"],"575":["Mangaluru","Karnataka"],"570":["Mysuru","Karnataka"],"403":["Panaji","Goa"],"831":["Jamshedpur","Jharkhand"]};
const SM=(t=>{const m={};t.split(",").forEach(x=>{const[r,n]=x.split(" "),[a,b]=r.split("-");for(let i=+a;i<=+(b||a);i++)m[i]=n.replace(/_/g," ")});return m})("11 Delhi,12-13 Haryana,14-16 Punjab,17 Himachal_Pradesh,18-19 Jammu_&_Kashmir,20-28 Uttar_Pradesh,30-34 Rajasthan,36-39 Gujarat,40-44 Maharashtra,45-48 Madhya_Pradesh,49 Chhattisgarh,50 Telangana,51-53 Andhra_Pradesh,56-59 Karnataka,60-64 Tamil_Nadu,67-69 Kerala,70-74 West_Bengal,75-77 Odisha,78 Assam,80 Bihar");
const cyl=(w,y,h,bg)=>{let s="";for(let i=0;i<h;i+=2)s+=`<div class="dk" style="width:${w}px;height:${w}px;margin:${-w/2}px 0 0 ${-w/2}px;background:${bg};transform:translateY(${50-y-i}px) rotateX(90deg)"></div>`;return s};
const pl=(x,y,w,h,bg,r)=>[0,90].map(a=>`<div class="dk" style="width:${w}px;height:${h}px;margin:${-h}px 0 0 ${x-w/2}px;border-radius:${r};background:${bg};transform:translateY(${50-y}px) rotateY(${a}deg)"></div>`).join("");
function cake3d(a,b){const g=(x,y)=>`conic-gradient(${x},${y},${x})`;
 let h=cyl(196,-8,6,"#f3e3d6")+cyl(150,0,44,g(a,b))+cyl(158,44,4,"#fff")+cyl(112,48,38,g(b,a))+cyl(120,86,4,"#fff")+cyl(76,90,30,g(a,b))+cyl(84,120,4,"#fff");
 [-16,0,16].forEach(x=>{h+=pl(x,124,6,26,"#ffd873","2px")+pl(x,150,9,13,"radial-gradient(#fff3a0,#ff9a3c)","50%")});
 return `<div class="scene" aria-hidden="true"><div class="w3"><div class="spin">${h}</div></div></div>`}

const EV=[["🎂","Birthday"],["💕","Anniversary"],["💍","Wedding"],["🏢","Corporate"],["🧸","Baby Shower"],["✨","Other"]];
const ST=["Order Placed","Order Confirmed","Preparing Your Order","Out for Delivery","Delivered"],SL=["10 AM – 12 PM","12 PM – 3 PM","3 PM – 6 PM","6 PM – 9 PM"];
const PAL=["#f3d9cc","#ffd3da","#ffe8b8","#fff3b0","#e3d4f0","#ffe0b0"];
const $=i=>document.getElementById(i),E=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c])),R=n=>"₹"+Number(n||0).toLocaleString("en-IN");
const iso=d=>d.getFullYear()+"-"+String(d.getMonth()+1).padStart(2,"0")+"-"+String(d.getDate()).padStart(2,"0"),ago=n=>{const d=new Date();d.setDate(d.getDate()-n);return iso(d)};
function conf(){const c=["#ef3e72","#ffd873","#7fd1b0","#a597ea"];$("cf").innerHTML=Array.from({length:44},()=>`<i style="left:${Math.random()*100}%;background:${c[Math.random()*4|0]};animation-delay:${Math.random()*.6}s"></i>`).join("");setTimeout(()=>$("cf").innerHTML="",3200)}
const chip=(t,k="")=>`<span class="chip ${k}">${t}</span>`;
const sChip=s=>s<0?chip("Cancelled","p"):chip(["Placed","Confirmed","Preparing","On the way","Delivered"][s],["w","b","b","p",""][s]);
const pChip=o=>o.s<0?(o.refund_status=="due"?chip("Refund pending","w"):o.refund_status=="done"?chip("Refunded ✔"):""):({pending:chip("Payment pending","w"),submitted:chip("Checking payment","b"),verified:chip("Paid ✔"),rejected:chip("Payment not received","p")})[o.pay_status]||"";
const tl=o=>o.s<0?"":`<div class="tl">${ST.map((x,i)=>`<div class="${i<=o.s?"d":""}">${x}</div>`).join("")}</div>`;
const errBox=()=>S.err?`<div class="err" role="alert">${E(S.err)}</div>`:"";
const TABS={guest:[["home","🏠","Home"],["orders","📦","Orders"],["acct","👤","Login"]],customer:[["home","🏠","Home"],["orders","📦","Orders"],["acct","👤","Account"]],seller:[["prods","🛍","Products"],["sorders","📦","Orders"]],delivery:[["dorders","🛵","Deliveries"]],admin:[["ov","📊","Overview"],["aorders","📦","Orders"],["ppl","👥","People"],["prods","🛍","Products"],["set","⚙️","Settings"]]};
const HOME={guest:"home",customer:"home",seller:"prods",delivery:"dorders",admin:"ov"};
let S={user:null,tab:"home",view:"",err:"",items:[],orders:[],prods:[],people:[],custs:[],pv:"s",dps:[],cfg:{},set:{},det:null,lab:null,open:null,pay:null,pid:0,after:null,draft:null,okmsg:"",notes:[],unread:0,refunds:[],cancel:0},FM={};
try{const x=JSON.parse(localStorage.getItem("wm4"));if(x&&x.user)S.user=x.user}catch(e){}
const saveU=()=>{try{localStorage.setItem("wm4",JSON.stringify({user:S.user}))}catch(e){}};
const SA=()=>{try{return JSON.parse(localStorage.getItem("wm4a"))||{}}catch(e){return{}}};
const role=()=>S.user?S.user.role:"guest";
async function api(p,m="GET",b){const r=await fetch("/api"+p,{method:m,headers:{"Content-Type":"application/json",...(S.user?{Authorization:"Bearer "+S.user.token}:{})},body:b?JSON.stringify(b):undefined});const j=await r.json().catch(()=>({}));
 if(r.status==401&&S.user&&p!="/login"){S.user=null;saveU();S.tab="home";S.view="login";FM={}}if(!r.ok)throw new Error(j.error||"Something went wrong. Please try again.");return j}
const imgUrl=p=>`/api/products/${p.id}/img?v=${p.upd}`;
const pic=(p,h)=>`<div class="pic" style="background:${PAL[p.id%PAL.length]};${h?"height:"+h+"px":""}">${p.hasimg?`<img src="${imgUrl(p)}" alt="${E(p.name)}" loading="lazy">`:"🎂"}</div>`;
const inp=(f,l,t="text",x="")=>`<label for="f_${f}">${l}</label><input type="${t}" id="f_${f}" data-f="${f}" value="${E(FM[f])}" ${x}>`;
const num=(f,l,n)=>inp(f,l,"tel",`inputmode="numeric" maxlength="${n}" autocomplete="off"`);
function go(tab,view){S.tab=tab;S.view=view||"";S.err="";S.det=null;S.pay=null;S.okmsg="";FM={};load()}
function startBook(pid){const a=SA();S.pid=pid;S.tab="home";S.view="book";S.err="";FM={qty:1,ev:0,date:ago(-1),slot:SL[1],msg:"Happy Birthday!",at:"Home",name:S.user?S.user.name:"",phone:"",pin:"",city:"",state:"",loc:"",house:"",street:"",land:"",...a}}
const hello=()=>`<div class="card"><b>${S.user?"Hi, "+E(S.user.name.split(" ")[0])+"! 🎉":"Welcome to Wishme 🎉"}</b><div class="mut">Cakes and party needs from local sellers.</div></div>`;
const prodCard=p=>`<button class="ck" data-a="pick" data-i="${p.id}">${pic(p)}<b>${E(p.name)}</b><span class="mut" style="display:block">${E(p.shop)}</span><span>${R(p.price)}${p.unit?" · "+E(p.unit):""}</span></button>`;
function home(){return `${hello()}<div class="hero"><div><h1>Plan Your Perfect Celebration</h1><p>Cakes • Decorations • Party needs</p></div>${cake3d(...CC[0])}</div><h2>Fresh from our sellers</h2>${S.items.length?`<div class="cakes">${S.items.map(prodCard).join("")}</div>`:'<div class="card mut">No products yet. Sellers will appear here soon.</div>'}
${role()=="guest"?`<div class="card"><h3>Want to sell or deliver?</h3><button class="btn full" data-a="join" data-v="sjoin">🛍 Sell on Wishme</button><button class="btn ghost full" data-a="join" data-v="djoin">🛵 Join as delivery partner</button></div>`:""}`}
function addrForm(){return `<div class="g2">${inp("name","Full name","text",'autocomplete="name"')}${num("phone","10-digit mobile",10)}</div><div class="g2">${num("pin","Pincode",6)}<div><label for="f_loc">Locality / Area</label><input type="text" id="f_loc" data-f="loc" value="${E(FM.loc)}" list="areas" autocomplete="off"><datalist id="areas"></datalist></div></div>
${inp("house","Flat / House no. / Building")}${inp("street","Road name / Street / Colony")}${inp("land","Landmark (optional)","text",'placeholder="Near temple, school, mall"')}<div class="g2">${inp("city","City / District")}${inp("state","State")}</div>
<div class="mut" style="margin-top:6px">City and state fill automatically from the pincode.</div><label>Address type</label>${["Home","Work"].map(x=>`<button class="ev ${FM.at==x?"on":""}" data-a="at" data-v="${x}" style="padding:8px 20px;margin-right:8px">${x}</button>`).join("")}`}
function bookView(){const p=S.items.find(x=>x.id==S.pid);if(!p)return `<div class="card">Product not found. <button class="btn sm" data-a="tab" data-v="home">Back</button></div>`;
 const t=new Date(),m=new Date();m.setDate(m.getDate()+10);const fee=+S.cfg.fee||0,tot=p.price*FM.qty+fee;
 return `<button class="btn sm ghost" data-a="tab" data-v="home">← Back</button><div class="card" style="margin-top:10px">${pic(p,150)}<h3 style="margin-top:8px">${E(p.name)}</h3><div class="mut">${E(p.shop)}${p.unit?" · "+E(p.unit):""}</div>${p.descr?`<div style="margin-top:4px">${E(p.descr)}</div>`:""}
 <div class="add"><div class="t"><b>${R(p.price)}</b> each</div><div class="qty"><button data-a="qty" data-d="-1" aria-label="Less">−</button>${FM.qty}<button data-a="qty" data-d="1" aria-label="More">+</button></div></div></div>
 <div class="card"><h3>Event details</h3><div class="row" style="margin-top:10px">${EV.map((e,i)=>`<button class="ev ${FM.ev==i?"on":""}" data-a="ev2" data-i="${i}"><div class="ic">${e[0]}</div>${e[1]}</button>`).join("")}</div>
 <div class="g2"><div><label for="f_date">Event date</label><input type="date" id="f_date" data-f="date" data-r="1" min="${iso(t)}" max="${iso(m)}" value="${FM.date}"></div><div><label for="f_slot">Delivery slot</label><select id="f_slot" data-f="slot" data-r="1">${SL.map(x=>`<option ${x==FM.slot?"selected":""}>${x}</option>`).join("")}</select></div></div><div class="mut" style="margin-top:6px">${FM.date<=iso(t)?"⚠️ Orders for today cannot be cancelled. ":""}You can cancel free until 1 day before the event date. Paid orders are refunded to your UPI or bank account.</div>${inp("msg","Message on cake / note","text",'maxlength="30"')}</div>
 <div class="card"><h3>📍 Delivery address</h3>${addrForm()}</div>
 <div class="card"><div class="tb"><span>Items (${FM.qty} × ${R(p.price)})</span><b>${R(p.price*FM.qty)}</b></div><div class="tb"><span>Delivery fee</span><b>${R(fee)}</b></div><div class="tot"><span>Total</span><span>${R(tot)}</span></div>${errBox()}<button class="btn full" data-a="place" ${FM.busy?"disabled":""}>${S.user?"Place order & pay":"Log in to place order"}</button></div>`}
async function placeOrder(){const p=S.items.find(x=>x.id==S.pid);S.err="";const d=Math.round((new Date(FM.date+"T00:00")-new Date(iso(new Date())+"T00:00"))/864e5);
 if(!(FM.name||"").trim())S.err="Enter your name.";else if(!/^\d{10}$/.test(FM.phone||""))S.err="Enter a 10-digit mobile number.";else if(isNaN(d)||d<0||d>10)S.err="Pick an event date within the next 10 days.";
 else if(!/^\d{6}$/.test(FM.pin||""))S.err="Enter a 6-digit pincode.";else if(!(FM.loc||"").trim()||!(FM.house||"").trim()||!(FM.street||"").trim())S.err="Fill locality, house no. and street.";else if(!(FM.city||"").trim()||!(FM.state||"").trim())S.err="Enter city and state.";
 if(S.err)return render();
 if(!S.user){S.draft=FM;S.after="book";S.view="login";FM={};return render()}
 FM.busy=1;render();
 try{const r=await api("/orders","POST",{product_id:p.id,qty:FM.qty,ev:FM.ev,date:FM.date,slot:FM.slot,msg:FM.msg,name:FM.name.trim(),phone:FM.phone,addr:[FM.house,FM.street,FM.loc,FM.land?"Near "+FM.land:"",FM.city,FM.state].filter(Boolean).join(", ")+" - "+FM.pin});
  try{localStorage.setItem("wm4a",JSON.stringify({name:FM.name,phone:FM.phone,pin:FM.pin,city:FM.city,state:FM.state,loc:FM.loc,house:FM.house,street:FM.street,land:FM.land,at:FM.at}))}catch(e){}
  S.orders=await api("/orders/mine");S.pay=r.id;S.view="pay";S.tab="orders";FM={}}catch(e){S.err=e.message;FM.busy=0}render()}
function payView(){const o=S.orders.find(x=>x.id==S.pay),c=S.cfg;if(!o)return '<div class="card mut">Loading your order…</div>';
 if(!c.upi_id)return `<div class="card"><h3>Order #WM${o.id} placed</h3><p>Online payment is not set up yet. The shop will contact you on ${E(o.cphone)}.</p><button class="btn" data-a="tab" data-v="orders">My orders</button></div>`;
 const link=`upi://pay?pa=${encodeURIComponent(c.upi_id)}&pn=${encodeURIComponent(c.upi_name)}&am=${o.total}&cu=INR&tn=${encodeURIComponent("Wishme WM"+o.id)}`;
 return `<div class="card" style="text-align:center"><h3>Pay ${R(o.total)} for order #WM${o.id}</h3><div class="mut">Pay to ${E(c.upi_name)} (${E(c.upi_id)})</div><div class="qr xl" data-t="${E(link)}" data-z="200" style="margin:12px auto"></div>
 <a class="btn full" href="${E(link)}">Pay with UPI app</a><div class="mut" style="margin-top:8px">On a phone tap the button. Or scan this QR from another phone.</div></div>
 <div class="card"><h3>After paying</h3><div class="mut">Enter the UPI transaction ID (UTR) shown in your payment app. The owner confirms it and your order starts.</div>${inp("utr","UPI transaction ID","text",'autocomplete="off" autocapitalize="characters"')}${errBox()}<button class="btn full" data-a="submitpay" data-i="${o.id}">I have paid</button><button class="btn ghost full" data-a="tab" data-v="orders" style="margin-top:8px">Pay later</button></div>`}
function custOrders(){if(!S.user)return `<div class="card" style="text-align:center"><h3>Log in to see your orders</h3><button class="btn" data-a="login">Log in</button></div>`;
 if(!S.orders.length)return `<div class="card" style="text-align:center"><div style="font-size:48px">🎂</div><h3>No orders yet</h3><button class="btn" data-a="tab" data-v="home">Browse cakes</button></div>`;
 return `<h2 style="margin-top:6px">Your orders</h2>${S.okmsg?`<div class="card" style="color:var(--gn);font-weight:600">${E(S.okmsg)}</div>`:""}`+S.orders.map((o,k)=>{const op=S.open==o.id||(S.open==null&&k==0);
 return `<div class="card"><button data-a="tg" data-i="${o.id}" style="all:unset;cursor:pointer;display:block;width:100%"><div style="display:flex;justify-content:space-between"><b>#WM${o.id}</b>${sChip(o.s)}</div><div class="mut">${EV[o.ev][1]} · ${o.date} · ${E(o.slot)}</div><div>${E(o.pname)} × ${o.qty} · <b>${R(o.total)}</b></div><div>${pChip(o)}</div></button>
 ${o.s>=0&&["pending","rejected"].includes(o.pay_status)?`<button class="btn sm" data-a="paynow" data-i="${o.id}" style="margin-top:8px">Pay ${R(o.total)} now</button>`:""}
 ${op?tl(o)+(o.dname&&o.s>=3?`<div class="dp"><div class="av">${E(o.dname[0])}</div><div><b>${E(o.dname)}</b><div class="mut">Delivery partner</div></div></div>`:"")+(o.s==3?`<p>Give OTP <b>${E(o.otp)}</b> to your delivery partner.</p>`:""):""}
 ${o.s<0&&o.refund_status=="due"?'<div class="mut">Refund is being processed. You will get a notification when it is sent.</div>':""}${o.s<0&&o.refund_status=="done"?`<div class="mut">Refund sent${o.refund_ref?" · Ref "+E(o.refund_ref):""}. It may take a few hours to show in your account.</div>`:""}
 ${o.can_cancel?(S.cancel==o.id?cxlForm(o):`<button class="btn sm ghost" data-a="cxl" data-i="${o.id}" style="margin-top:8px;color:#dc2626;border-color:#dc2626">Cancel order</button>`):(o.s>=0&&o.s<=2?'<div class="mut" style="margin-top:6px">Cancellation closed (less than 1 day to the event).</div>':"")}</div>`}).join("")}
function cxlForm(o){const paid=["verified","submitted"].includes(o.pay_status);return `<div style="margin-top:10px;border-top:1px solid var(--line);padding-top:8px"><b>Cancel order #WM${o.id}?</b>${paid?`<div class="mut">Your ${R(o.total)} will be refunded. Where should we send it?</div><div style="display:flex;gap:6px;margin:8px 0">${[["upi","UPI ID"],["bank","Bank account"]].map(x=>`<button class="btn sm ${(FM.mode||"upi")==x[0]?"":"ghost"}" data-a="rmode" data-v="${x[0]}">${x[1]}</button>`).join("")}</div>${(FM.mode||"upi")=="upi"?inp("upi","Your UPI ID for refund (name@bank)","text",'autocapitalize="none" autocomplete="off"'):inp("holder","Account holder name")+num("acct","Account number",18)+inp("ifsc","IFSC code","text",'maxlength="11" autocapitalize="characters"')}`:'<div class="mut">No payment was made, so nothing to refund.</div>'}${errBox()}<button class="btn full" data-a="cxlgo" data-i="${o.id}" style="background:#dc2626">Yes, cancel order</button><button class="btn ghost full" data-a="cxl" data-i="${o.id}" style="margin-top:8px">Keep my order</button></div>`}
function notesView(){return `<button class="btn sm ghost" data-a="tab" data-v="${S.tab}">← Back</button><h2 style="margin-top:10px">🔔 Notifications</h2>`+(S.notes.map(n=>`<div class="card" style="${n.rd?"":"border-left:4px solid var(--pk)"}"><div>${E(n.txt)}</div><div class="mut">${new Date(n.t).toLocaleString("en-IN",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"})}</div></div>`).join("")||'<div class="card mut">No notifications yet. Order updates will appear here.</div>')}
function refundsView(){const due=S.refunds.filter(r=>r.refund_status=="due"),dn=S.refunds.filter(r=>r.refund_status=="done").slice(0,5);if(!S.refunds.length)return "";
 return `<div class="card" style="border:2px solid ${due.length?"#dc2626":"var(--line)"}"><h3>💸 Refunds ${due.length?`(${due.length} to pay)`:""}</h3>`+due.map(r=>{const t=r.to||{};return `<div style="border-top:1px solid var(--line);margin-top:8px;padding-top:8px"><b>#WM${r.id}</b> · <b>${R(r.total)}</b> · ${E(r.cname)} · ${E(r.cphone)}<br>${t.mode=="bank"?`<span class="mut">Bank: ${E(t.holder)} · A/c <b>${E(t.acct)}</b> · IFSC ${E(t.ifsc)}</span>`:t.mode=="upi"?`<span class="mut">UPI: <b>${E(t.upi)}</b></span><br><a class="btn sm" style="display:inline-block;margin-top:6px;text-decoration:none" href="${E(`upi://pay?pa=${encodeURIComponent(t.upi)}&pn=${encodeURIComponent(r.cname)}&am=${r.total}&cu=INR&tn=${encodeURIComponent("Wishme refund WM"+r.id)}`)}">Pay refund in UPI app</a>`:""}<input id="rf_${r.id}" type="text" placeholder="Refund transaction ID (optional)" style="margin-top:8px"><button class="btn sm gn" data-a="rfd" data-i="${r.id}" style="margin-top:6px">✔ Refund sent</button></div>`}).join("")+(dn.length?`<div class="mut" style="margin-top:8px">Done: ${dn.map(r=>"#WM"+r.id).join(", ")}</div>`:"")+`</div>`}
function acct(){if(S.user)return `<div class="card"><h3>${E(S.user.name)}</h3><div class="mut">Customer account</div><button class="btn full" data-a="logout">Log out</button></div>`;return loginView()}
function loginView(){const reg=S.view=="reg";return `<div style="text-align:center">${cake3d(...CC[0])}</div><div class="card"><h3>${reg?"Create your account":"Log in"}</h3>${S.after?'<div class="mut">Log in to place your order. Your details are saved.</div>':""}${reg?inp("name","Your name","text",'autocomplete="name"'):""}${num("phone","10-digit mobile",10)}${inp("password","Password","password",`autocomplete="${reg?"new-password":"current-password"}"`)}${errBox()}
 <button class="btn full" data-a="${reg?"doreg":"dologin"}">${reg?"Create account":"Log in"}</button><button class="btn sm alt" data-a="${reg?"showlogin":"showreg"}" style="margin-top:12px">${reg?"I already have an account":"New here? Create account"}</button></div>
 <div class="card"><button class="btn ghost full" data-a="join" data-v="sjoin">🛍 Sell on Wishme</button><button class="btn ghost full" data-a="join" data-v="djoin" style="margin-top:8px">🛵 Join as delivery partner</button></div>`}
function done(){return `<div class="card" style="text-align:center"><div style="font-size:48px">✅</div><h3>Application sent</h3><p>The owner will check your details. You can log in after approval, using the same mobile number and password.</p><button class="btn" data-a="tab" data-v="home">Back to home</button></div>`}
function sjoin(){return `<button class="btn sm ghost" data-a="tab" data-v="home">← Back</button><div class="card" style="margin-top:10px"><h3>🛍 Sell on Wishme</h3><div class="mut">The owner approves every seller. After approval you add products, prices and photos.</div>${inp("name","Your name")}${num("phone","10-digit mobile",10)}${inp("password","Create password (6+ characters)","password",'autocomplete="new-password"')}${inp("shop","Shop / brand name")}${inp("address","Full shop address")}${inp("upi","Your UPI ID for payouts (name@bank)","text",'autocapitalize="none"')}${num("fssai","FSSAI licence no. (14 digits, needed for food)",14)}${errBox()}<button class="btn full" data-a="apps">Send application</button></div>`}
const DOCS=[["aadhaar","Aadhaar card photo"],["pan","PAN card photo"],["passbook","Bank passbook first page"],["selfie","Your selfie"]];
function djoin(){const d=FM.docs||{};return `<button class="btn sm ghost" data-a="tab" data-v="home">← Back</button><div class="card" style="margin-top:10px"><h3>🛵 Join as delivery partner</h3><div class="mut">Your details are encrypted and only the owner can see them. The owner approves every partner.</div>${inp("name","Full name (as on PAN)")}${num("phone","10-digit mobile",10)}${inp("password","Create password (6+ characters)","password",'autocomplete="new-password"')}${inp("addr","Full home address")}
 ${inp("pan","PAN number","text",'maxlength="10" autocapitalize="characters"')}${num("aadhaar","Aadhaar number (only last 4 digits are kept)",12)}<h3 style="margin-top:14px">Bank details for payment</h3>${inp("holder","Account holder name")}${num("acct","Account number",18)}${inp("ifsc","IFSC code","text",'maxlength="11" autocapitalize="characters"')}
 <h3 style="margin-top:14px">Document photos</h3>${DOCS.map(x=>`<label for="d_${x[0]}">${x[1]} ${d[x[0]]?"✅":""}</label><input type="file" id="d_${x[0]}" accept="image/*" data-doc="${x[0]}">${d[x[0]]?`<img src="${d[x[0]]}" alt="${x[1]}" style="width:100%;max-height:150px;object-fit:contain;margin-top:6px;border-radius:10px">`:""}`).join("")}${errBox()}<button class="btn full" data-a="appd">Send application</button></div>`}
function prodsView(){const own=role()=="admin"?"Your own products (no commission)":"Your products";return `<h2 style="margin-top:6px">${own}</h2><div class="card"><h3>Add a product</h3>${inp("name","Product name","text",'maxlength="80"')}${inp("descr","Short description","text",'maxlength="300"')}<div class="g2">${num("price","Price (₹)",6)}${inp("unit","Size / weight (e.g. 1 kg)","text",'maxlength="30"')}</div>
 <label for="p_img">Photo</label><input type="file" id="p_img" accept="image/*">${FM.img?`<img src="${FM.img}" alt="Preview" style="width:100%;max-height:160px;object-fit:cover;margin-top:6px;border-radius:12px">`:""}${errBox()}<button class="btn full" data-a="addprod">Add product</button></div>
 ${S.prods.map(p=>`<div class="card"><div style="display:flex;gap:10px"><div style="width:72px">${pic(p,72)}</div><div style="flex:1"><b>${E(p.name)}</b><div class="mut">${E(p.unit)} ${p.active?"":"· hidden"}</div><div style="display:flex;gap:6px;margin-top:6px"><input id="pr_${p.id}" type="tel" inputmode="numeric" value="${p.price}" aria-label="Price" style="width:90px"><button class="btn sm" data-a="saveprod" data-i="${p.id}">Save price</button></div></div></div><button class="btn sm ghost" data-a="tgprod" data-i="${p.id}" data-v="${p.active?0:1}" style="margin-top:8px">${p.active?"Hide from shop":"Show in shop"}</button> <button class="btn sm ghost" data-a="delprod" data-i="${p.id}" style="margin-top:8px;color:#dc2626;border-color:#dc2626">🗑 Delete</button></div>`).join("")||'<div class="card mut">No products yet. Add your first one above.</div>'}`}
function sOrders(){const dn=S.orders.filter(o=>o.s==4),due=dn.filter(o=>!o.seller_paid).reduce((a,o)=>a+o.seller_amt,0);
 return `<h2 style="margin-top:6px">Orders</h2><div class="stats"><div class="card"><b>${S.orders.filter(o=>o.s>=0&&o.s<4).length}</b><span>Active</span></div><div class="card"><b>${R(due)}</b><span>To be paid to you</span></div></div><div style="height:12px"></div>`+(S.orders.map(o=>`<div class="card"><div style="display:flex;justify-content:space-between"><b>#WM${o.id}</b>${sChip(o.s)}</div><div><b>${E(o.pname)} × ${o.qty}</b></div><div class="mut">${EV[o.ev][1]} · ${o.date} · ${E(o.slot)}<br>Write on cake: "${E(o.msg)}"<br>You get ${R(o.seller_amt)} (after ${R(o.commission)} commission)${o.s==4?(o.seller_paid?" · paid ✔":" · payout due"):""}</div>${o.s==1?`<button class="btn sm" data-a="prep" data-i="${o.id}" style="margin-top:8px">Start preparing</button>`:""}${o.s<0?'<div class="mut" style="color:#dc2626">Cancelled by customer. Do not prepare.</div>':""}${o.s==2?'<div class="mut">Ready soon? The owner will send a delivery partner.</div>':""}</div>`).join("")||'<div class="card mut">No paid orders yet.</div>')}
function dOrders(){const act=S.orders.filter(o=>o.s==3);return `<h2 style="margin-top:6px">Deliveries</h2><div class="stats"><div class="card"><b>${act.length}</b><span>Active</span></div><div class="card"><b>${S.orders.filter(o=>o.s==4).length}</b><span>Delivered</span></div></div><div style="height:12px"></div>`+
 (act.map(o=>`<div class="card"><div style="display:flex;justify-content:space-between"><b>#WM${o.id}</b>${sChip(o.s)}</div><div>${E(o.pname)} × ${o.qty}</div><div class="mut">Pick up: ${E(o.shop)}, ${E(o.saddr)}</div><div style="margin-top:6px"><b>${E(o.cname)}</b> · <a href="tel:${E(o.cphone)}">📞 ${E(o.cphone)}</a></div><div class="mut">${E(o.addr)} · ${E(o.slot)}</div><div class="mut">Already paid online. Do not collect cash.</div>
 <label for="o${o.id}">Customer OTP</label><input type="text" id="o${o.id}" inputmode="numeric" maxlength="4"><button class="btn gn full" data-a="dl" data-i="${o.id}">Mark delivered</button></div>`).join("")||'<div class="card mut">No active deliveries. New ones appear here when the owner sends them to you.</div>')+errBox()}
function ov(){const os=S.orders,ok=os.filter(o=>o.pay_status=="verified"&&o.s>=0),dn=os.filter(o=>o.s==4),earn=dn.reduce((a,o)=>a+o.commission+o.fee,0),due=dn.filter(o=>!o.seller_paid).reduce((a,o)=>a+o.seller_amt,0),
 days=[...Array(7)].map((_,i)=>ago(6-i)),v=days.map(d=>ok.filter(o=>o.created==d).reduce((a,o)=>a+o.total,0)),mx=Math.max(...v,1),chk=os.filter(o=>o.pay_status=="submitted").length,pen=S.people.filter(p=>p.status=="pending").length,rf=S.refunds.filter(r=>r.refund_status=="due").length;
 return `<h2 style="margin-top:6px">Overview</h2>${chk||pen||rf?`<div class="card" style="border:2px solid var(--pk)">${rf?`<div>💸 <b>${rf}</b> refund(s) to pay → Orders tab</div>`:""}${chk?`<div>💰 <b>${chk}</b> payment(s) to check → Orders tab</div>`:""}${pen?`<div>👥 <b>${pen}</b> application(s) waiting → People tab</div>`:""}</div>`:""}
 <div class="stats"><div class="card"><b>${os.length}</b><span>Total orders</span></div><div class="card"><b>${R(ok.reduce((a,o)=>a+o.total,0))}</b><span>Paid sales</span></div><div class="card"><b>${R(earn)}</b><span>Your earnings (delivered)</span></div><div class="card"><b>${R(due)}</b><span>Owed to sellers</span></div></div>
 <div class="card" style="margin-top:12px"><h3>Paid sales, last 7 days</h3><svg viewBox="0 0 280 110" width="100%" role="img" aria-label="Sales bar chart">${v.map((x,i)=>`<rect x="${i*40+8}" y="${90-x/mx*80}" width="26" height="${x/mx*80}" rx="5" fill="#ef3e72"/><text x="${i*40+21}" y="105" font-size="9" text-anchor="middle" fill="currentColor">${days[i].slice(8)}</text>`).join("")}</svg></div>`}
function aOrders(){return `<h2 style="margin-top:6px">Orders</h2>`+refundsView()+(S.orders.map(o=>`<div class="card"><div style="display:flex;justify-content:space-between;gap:6px"><b>#WM${o.id}</b><span>${sChip(o.s)} ${pChip(o)}</span></div><div>${E(o.pname)} × ${o.qty} · <b>${R(o.total)}</b></div>
 <div class="mut">${E(o.shop)} → ${E(o.cname)} · ${E(o.cphone)}<br>${EV[o.ev][1]} · ${o.date} · ${E(o.slot)} · "${E(o.msg)}"<br>You earn ${R(o.commission+o.fee)} · Seller gets ${R(o.seller_amt)}</div>${o.utr?`<div class="mut">UPI transaction ID: <b>${E(o.utr)}</b> (check ${R(o.total)} in your account)</div>`:""}
 ${o.pay_status=="submitted"&&o.s>=0?`<button class="btn sm gn" data-a="vp" data-i="${o.id}">✔ Payment received</button> <button class="btn sm ghost" data-a="rj" data-i="${o.id}">✖ Not received</button>`:""}
 ${o.s==2?`<select id="dv_${o.id}" aria-label="Delivery partner" style="margin-top:8px"><option value="">Choose delivery partner</option>${S.dps.map(d=>`<option value="${d.id}">${E(d.name)}</option>`).join("")}</select><button class="btn sm" data-a="send" data-i="${o.id}" style="margin-top:8px">Send out for delivery</button>`:""}
 ${o.s==3?`<div class="mut">With ${E(o.dname||"")}</div>`:""}${o.s==4&&!o.seller_paid&&o.seller_amt>0?`<button class="btn sm" data-a="sp" data-i="${o.id}">Mark seller paid ${R(o.seller_amt)}</button>`:""}
 ${o.pay_status=="verified"&&o.s>=0?`<button class="btn sm ghost" data-a="lb" data-i="${o.id}">🏷 Label</button>`:""} <a class="btn sm ghost" style="text-decoration:none;display:inline-block" target="_blank" rel="noopener" href="https://wa.me/91${E(o.cphone)}?text=${encodeURIComponent("Wishme: about your order #WM"+o.id+" ")}">💬 WhatsApp</a></div>`).join("")||'<div class="card mut">No orders yet.</div>')}
function custs(){return `<div class="mut">${S.custs.length} customer(s)</div>`+(S.custs.map(c=>`<div class="card"><div style="display:flex;justify-content:space-between"><b>${E(c.name)}</b><span class="mut">Joined ${E(c.created||"")}</span></div><div><a href="tel:${E(c.phone)}">📞 ${E(c.phone)}</a></div><div class="mut">${c.orders} order(s) · Paid ${R(c.spent)}</div></div>`).join("")||'<div class="card mut">No customers yet.</div>')}
function ppl(){const tg=`<div class="seg" style="display:flex;gap:6px;margin:8px 0">${[["s","Sellers & delivery"],["c","Customers"]].map(x=>`<button data-a="pv" data-v="${x[0]}" class="btn sm ${S.pv==x[0]?"":"ghost"}">${x[1]}</button>`).join("")}</div>`;if(S.pv=="c")return `<h2 style="margin-top:6px">People</h2>${tg}${custs()}`;return `<h2 style="margin-top:6px">People</h2>${tg}`+(S.people.map(p=>`<div class="card"><div style="display:flex;justify-content:space-between"><b>${E(p.name)}</b>${chip(p.role=="seller"?"Seller":"Delivery",p.role=="seller"?"b":"p")} </div><div class="mut">${E(p.phone)}${p.shop?" · "+E(p.shop):""} · ${chip(p.status,p.status=="active"?"":"w")}</div>
 <button class="btn sm ghost" data-a="kyc" data-i="${p.id}" style="margin-top:8px">View details</button>${p.status!="active"?`<button class="btn sm gn" data-a="setst" data-i="${p.id}" data-v="active" style="margin-left:6px">Approve</button>`:""}${p.status=="pending"?`<button class="btn sm ghost" data-a="setst" data-i="${p.id}" data-v="rejected" style="margin-left:6px">Reject</button>`:""}${p.status=="active"?`<button class="btn sm ghost" data-a="setst" data-i="${p.id}" data-v="blocked" style="margin-left:6px">Block</button>`:""}</div>`).join("")||'<div class="card mut">No sellers or delivery partners yet.</div>')}
function setView(){return `<h2 style="margin-top:6px">Settings</h2><div class="card"><h3>Where customers pay</h3><div class="mut">Money goes straight to this UPI ID. Check it matches your QR.</div>${inp("upi_id","Your UPI ID","text",'autocapitalize="none" placeholder="8676849002@upi"')}${inp("upi_name","Name shown while paying")}<h3 style="margin-top:14px">WhatsApp updates</h3><div class="mut">${S.set.wa_on?"✅ ON. Customers get order updates on WhatsApp.":"Not connected yet. Customers still get in-app notifications, and you can message them with the 💬 WhatsApp button on each order. To switch on automatic WhatsApp, add WA_TOKEN and WA_PHONE_ID in Render (see README)."}</div><h3 style="margin-top:14px">Money rules</h3><div class="g2">${num("fee","Delivery fee (₹)",3)}${inp("commission","Your commission on seller items (%)","text",'inputmode="decimal" maxlength="4"')}</div>${errBox()}${S.okmsg?`<div style="color:var(--gn);font-weight:600">${E(S.okmsg)}</div>`:""}<button class="btn full" data-a="saveset">Save settings</button></div>`}
function label(o){return `<div class="lbl"><div class="lh"><b>🎂 Wishme</b><b>#WM${o.id}</b></div><div class="lq"><div class="qr" data-t="WISHME|WM${o.id}"></div><div><b>${E(o.cname)}</b><br>📞 ${E(o.cphone)}<br>${E(o.addr)}</div></div><div class="lm"><b>${E(o.pname)} × ${o.qty}</b><br>${EV[o.ev][1]} · Msg: "${E(o.msg)}"<br>From: ${E(o.shop)}</div><div class="lf"><span>📅 ${o.date} · ${E(o.slot)}</span><b>PAID ✔</b></div><div class="lw">FRAGILE · KEEP UPRIGHT · HANDLE WITH CARE</div></div>`}
function overlay(){if(S.lab){const o=S.orders.find(x=>x.id==S.lab);return o?label(o)+`<div class="nop"><button class="btn" data-a="pr">🖨 Print label</button><button class="btn ghost" data-a="cd" style="background:#fff">Close</button></div>`:""}
 if(S.det){const d=S.det,k=d.kyc,s=d.seller;return `<div class="lbl" style="max-width:420px"><div class="lh"><b>${E(d.user.name)} · ${d.user.role}</b><b>${E(d.user.status)}</b></div><div>📞 ${E(d.user.phone)}</div>${s?`<div class="lm">Shop: <b>${E(s.shop)}</b><br>${E(s.address)}<br>UPI: ${E(s.upi)}<br>FSSAI: ${E(s.fssai||"not given")}</div>`:""}
 ${k?`<div class="lm">PAN: <b>${E(k.pan)}</b><br>Aadhaar: XXXX XXXX ${E(k.aadhaar4)}<br>Bank: ${E(k.holder)}<br>A/c: <b>${E(k.acct)}</b> · IFSC ${E(k.ifsc)}<br>Address: ${E(k.addr)}</div>${Object.entries(k.docs||{}).map(([n,u])=>`<div class="lm"><b>${E(n)}</b><img src="${E(u)}" alt="${E(n)}" style="width:100%;margin-top:4px"></div>`).join("")}`:(s?"":'<div class="lm">No KYC on file.</div>')}</div><div class="nop"><button class="btn ghost" data-a="cd" style="background:#fff">Close</button></div>`}return ""}
function view(){const v=S.view;if(v=="book")return bookView();if(v=="pay")return payView();if(v=="notes")return notesView();if(v=="login"||v=="reg")return loginView();if(v=="sjoin")return sjoin();if(v=="djoin")return djoin();if(v=="done")return done();
 return ({home,orders:custOrders,acct,prods:prodsView,sorders:sOrders,dorders:dOrders,ov,aorders:aOrders,ppl,set:setView})[S.tab]()}
function drawQR(){document.querySelectorAll(".qr[data-t]").forEach(el=>{if(el.dataset.d==el.dataset.t)return;el.innerHTML="";el.classList.remove("lg");const z=+el.dataset.z||96;if(window.QRCode){try{new QRCode(el,{text:el.dataset.t,width:z,height:z,colorDark:"#4a1230",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.H});el.classList.add("lg");el.dataset.d=el.dataset.t}catch(e){el.textContent="QR"}}else el.textContent=el.dataset.t.split("|")[1]||"QR"})}
function render(){const r=role();$("seg").innerHTML=S.user?`<button data-a="bell" aria-label="Notifications" style="background:none;border:0;font-size:19px;position:relative;padding:0 8px">🔔${S.unread?`<b style="position:absolute;top:-6px;right:0;background:var(--pk);color:#fff;border-radius:99px;font-size:10px;padding:0 5px">${S.unread}</b>`:""}</button><span class="mut">${E(S.user.name.split(" ")[0])}</span> <button data-a="logout">Log out</button>`:`<button data-a="login">Log in</button>`;
 const tabs=TABS[r],hide=!!S.view&&!["pay"].includes(S.view);$("nav").style.display=hide?"none":"flex";$("nav").innerHTML=tabs.map(t=>`<button data-a="tab" data-v="${t[0]}" class="${S.tab==t[0]?"on":""}"><span>${t[1]}</span>${t[2]}</button>`).join("");
 $("app").innerHTML=view();$("lab").innerHTML=overlay();drawQR()}
async function load(){if(S.user&&S.view!="notes")api("/notifications").then(r=>{const ch=r.unread!=S.unread;S.unread=r.unread;S.notes=r.items;if(ch&&!S.view&&!/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName))render()}).catch(()=>{});try{const t=S.tab;if(!S.cfg.ok){S.cfg=await api("/config");S.cfg.ok=1}
 if(S.view&&!["pay"].includes(S.view)){render();return}
 if(t=="home")S.items=await api("/products");else if(t=="orders"&&S.user)S.orders=await api("/orders/mine");else if(t=="prods")S.prods=await api("/seller/products");else if(t=="sorders")S.orders=await api("/seller/orders");else if(t=="dorders")S.orders=await api("/delivery/orders");
 else if(t=="ov"||t=="aorders"){const[o,d,p,rf]=await Promise.all([api("/admin/orders"),api("/admin/delivery"),api("/admin/people"),api("/admin/refunds")]);S.orders=o;S.dps=d;S.people=p;S.refunds=rf}else if(t=="ppl"){const[p,c]=await Promise.all([api("/admin/people"),api("/admin/customers")]);S.people=p;S.custs=c}
 else if(t=="set"){S.set=await api("/admin/settings");if(!FM.__s)FM={...S.set,__s:1}}
 if(S.view=="pay"&&S.user)S.orders=await api("/orders/mine")}catch(e){S.err=e.message}render()}
const act=async(fn,okf)=>{S.err="";try{await fn();if(okf)okf()}catch(e){S.err=e.message;alert(e.message)}load()};
function afterAuth(r){S.user={token:r.token,role:r.role,name:r.name};saveU();S.err="";if(S.after&&S.draft&&r.role=="customer"){FM=S.draft;S.view="book";S.tab="home";S.after=null;S.draft=null;FM.name=FM.name||r.name;load()}else{S.after=null;S.draft=null;S.view="";S.tab=HOME[r.role]||"home";FM={};load()}}
const A={tab:b=>go(b.dataset.v),login:()=>{S.tab="acct";S.view="login";S.err="";FM={};render()},showreg:()=>{S.view="reg";S.err="";FM={};render()},showlogin:()=>{S.view="login";S.err="";FM={};render()},
 logout:()=>{S.user=null;saveU();S.orders=[];S.after=null;S.draft=null;go("home")},join:b=>{S.view=b.dataset.v;S.tab="acct";S.err="";FM={docs:{}};render()},
 dologin:async()=>{S.err="";try{afterAuth(await api("/login","POST",{phone:FM.phone||"",password:FM.password||""}))}catch(e){S.err=e.message;render()}},
 doreg:async()=>{S.err="";try{afterAuth(await api("/register","POST",{name:FM.name||"",phone:FM.phone||"",password:FM.password||""}))}catch(e){S.err=e.message;render()}},
 apps:async()=>{S.err="";try{await api("/apply/seller","POST",{...FM});S.view="done";FM={}}catch(e){S.err=e.message}render()},
 appd:async()=>{S.err="";try{await api("/apply/delivery","POST",{...FM});S.view="done";FM={}}catch(e){S.err=e.message}render()},
 pick:(b,i)=>startBook(i),qty:b=>{FM.qty=Math.max(1,Math.min(20,FM.qty+ +b.dataset.d))},ev2:(b,i)=>{FM.ev=i},at:b=>{FM.at=b.dataset.v},place:placeOrder,
 paynow:(b,i)=>{S.pay=i;S.view="pay";S.tab="orders";FM={};S.err="";load()},
 submitpay:(b,i)=>{S.err="";api("/orders/"+i+"/pay","POST",{utr:FM.utr||""}).then(()=>{S.view="";S.pay=null;FM={};S.okmsg="Thanks! We are checking your payment. Your order starts as soon as it is confirmed.";S.tab="orders";conf();load()}).catch(e=>{S.err=e.message;render()})},
 tg:(b,i)=>{S.open=S.open==i?0:i},
 addprod:async()=>{S.err="";try{await api("/seller/products","POST",{name:FM.name,descr:FM.descr,price:FM.price,unit:FM.unit,img:FM.img});FM={};conf()}catch(e){S.err=e.message}load()},
 saveprod:(b,i)=>act(()=>api("/seller/products/"+i,"PATCH",{price:$("pr_"+i).value})),tgprod:(b,i)=>act(()=>api("/seller/products/"+i,"PATCH",{active:+b.dataset.v})),
 delprod:(b,i)=>{if(confirm("Delete this product for good? Old orders stay safe."))act(()=>api("/seller/products/"+i,"DELETE"))},
 pv:b=>{S.pv=b.dataset.v},
 bell:()=>{S.view="notes";S.err="";api("/notifications").then(r=>{S.notes=r.items;S.unread=0;render();api("/notifications/read","POST").catch(()=>{})}).catch(e=>alert(e.message))},
 cxl:(b,i)=>{S.cancel=S.cancel==i?0:i;FM={mode:"upi"};S.err=""},rmode:b=>{FM.mode=b.dataset.v;S.err=""},
 cxlgo:(b,i)=>{const o=S.orders.find(x=>x.id==i),paid=o&&["verified","submitted"].includes(o.pay_status);S.err="";api("/orders/"+i+"/cancel","POST",{mode:FM.mode,upi:FM.upi,acct:FM.acct,ifsc:FM.ifsc,holder:FM.holder}).then(()=>{S.cancel=0;FM={};S.okmsg="Order cancelled."+(paid?" Your refund will be sent soon.":"");load()}).catch(e=>{S.err=e.message;render()})},
 rfd:(b,i)=>act(()=>api("/admin/orders/"+i+"/refund","PATCH",{ref:$("rf_"+i).value}),conf),
 prep:(b,i)=>act(()=>api("/seller/orders/"+i+"/prepare","PATCH")),vp:(b,i)=>act(()=>api("/admin/orders/"+i+"/payment","PATCH",{action:"verify"}),conf),rj:(b,i)=>act(()=>api("/admin/orders/"+i+"/payment","PATCH",{action:"reject"})),
 send:(b,i)=>act(()=>api("/admin/orders/"+i+"/send","PATCH",{delivery_id:$("dv_"+i).value})),sp:(b,i)=>act(()=>api("/admin/orders/"+i+"/seller-paid","PATCH")),
 setst:(b,i)=>act(()=>api("/admin/users/"+i,"PATCH",{status:b.dataset.v})),kyc:(b,i)=>{api("/admin/kyc/"+i).then(d=>{S.det=d;render()}).catch(e=>alert(e.message))},
 cd:()=>{S.det=null;S.lab=null},lb:(b,i)=>{S.lab=i},pr:()=>{try{window.print()}catch(e){}},
 saveset:async()=>{S.err="";S.okmsg="";try{await api("/admin/settings","PUT",{upi_id:FM.upi_id,upi_name:FM.upi_name,fee:FM.fee,commission:FM.commission});S.okmsg="Saved ✔";S.cfg={}}catch(e){S.err=e.message}render();S.cfg=await api("/config").catch(()=>({}));S.cfg.ok=1},
 dl:async(b,i)=>{S.err="";try{await api("/delivery/orders/"+i+"/deliver","POST",{otp:$("o"+i).value.trim()});conf()}catch(e){S.err=e.message}load()}};
document.addEventListener("click",e=>{const b=e.target.closest("[data-a]");if(!b||/^(INPUT|SELECT)$/.test(b.tagName))return;const f=A[b.dataset.a];if(!f)return;f(b,+b.dataset.i);render()});
function shrink(file,max,q){return new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const k=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.round(im.width*k);c.height=Math.round(im.height*k);c.getContext("2d").drawImage(im,0,0,c.width,c.height);ok(c.toDataURL("image/jpeg",q))};im.onerror=()=>no(new Error("Could not read this photo."));im.src=r.result};r.onerror=()=>no(new Error("Could not read this photo."));r.readAsDataURL(file)})}
async function pinFetch(pin){try{const r=await fetch("https://api.postalpincode.in/pincode/"+pin),j=await r.json(),po=j[0]&&j[0].PostOffice;if(FM.pin!=pin||!po||!po.length||!$("f_city"))return;FM.city=po[0].District;FM.state=po[0].State;$("f_city").value=FM.city;$("f_state").value=FM.state;$("areas").innerHTML=po.map(x=>`<option value="${E(x.Name)}">`).join("");if(po.length==1&&!(FM.loc||"").trim()){FM.loc=po[0].Name;$("f_loc").value=FM.loc}}catch(e){}}
document.addEventListener("input",e=>{const t=e.target,f=t.dataset.f;if(!f||t.dataset.r)return;let v=t.value;if(["phone","pin","aadhaar","acct","fssai","fee","price"].includes(f))v=t.value=v.replace(/\D/g,"");if(f=="pan"||f=="ifsc"){v=t.value=v.toUpperCase()}FM[f]=v;
 if(f=="pin"&&v.length==6&&$("f_city")){const x=PC[v.slice(0,3)],st=SM[+v.slice(0,2)];if(x||st){FM.city=x?x[0]:FM.city;FM.state=x?x[1]:st;$("f_city").value=FM.city||"";$("f_state").value=FM.state||""}pinFetch(v)}});
document.addEventListener("change",async e=>{const t=e.target;if(t.type=="file"){const fl=t.files[0];if(!fl)return;try{const d=await shrink(fl,t.dataset.doc?1100:900,.7);if(t.dataset.doc){FM.docs=FM.docs||{};FM.docs[t.dataset.doc]=d}else FM.img=d;S.err=""}catch(x){S.err=x.message}render();return}
 const f=t.dataset.f;if(f&&t.dataset.r){FM[f]=t.value;render()}});
render();load();setInterval(()=>{if(!S.view&&!/INPUT|SELECT|TEXTAREA/.test(document.activeElement.tagName))load()},20000);
