const express=require("express"),Database=require("better-sqlite3"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken"),crypto=require("crypto");
const SECRET=process.env.JWT_SECRET||crypto.randomBytes(32).toString("hex");
if(!process.env.JWT_SECRET)console.warn("Set JWT_SECRET so staff logins survive restarts.");
const db=new Database(process.env.DB_PATH||"wishme.db");db.pragma("journal_mode = WAL");
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY,name TEXT,phone TEXT UNIQUE,pass TEXT,role TEXT);
CREATE TABLE IF NOT EXISTS orders2(id INTEGER PRIMARY KEY,token TEXT,cust TEXT,phone TEXT,ev INT,cake TEXT,kg REAL,extras TEXT,date TEXT,slot TEXT,msg TEXT,addr TEXT,total INT,pay TEXT,s INT DEFAULT 0,otp TEXT,delivery_id INT,created TEXT);`);
if(process.env.ADMIN_PHONE&&process.env.ADMIN_PASS){const h=bcrypt.hashSync(process.env.ADMIN_PASS,10),a=db.prepare("SELECT id FROM users WHERE phone=?").get(process.env.ADMIN_PHONE);
 if(a)db.prepare("UPDATE users SET pass=?,role='admin' WHERE id=?").run(h,a.id);else db.prepare("INSERT INTO users(name,phone,pass,role) VALUES('Owner',?,?,'admin')").run(process.env.ADMIN_PHONE,h)}
else console.warn("Set ADMIN_PHONE and ADMIN_PASS to create the owner login.");
const CAKES={"Chocolate Truffle":499,"Red Velvet":599,"Butterscotch":549,"Pineapple":449,"Black Forest":520,"Mango Delight":580};
const ADDON=[["Decoration",1500],["Food Menu",2000],["Balloons",300],["Photography",1200]];
const SLOTS=["10 AM – 12 PM","12 PM – 3 PM","3 PM – 6 PM","6 PM – 9 PM"];
const app=express();app.set("trust proxy",1);app.disable("x-powered-by");app.use(express.json({limit:"20kb"}));
app.use((q,r,n)=>{r.setHeader("X-Content-Type-Options","nosniff");n()});
const bad=(res,m,c=400)=>res.status(c).json({error:m});
const hits=new Map();setInterval(()=>hits.clear(),36e5).unref();
const limit=(max,ms)=>(q,r,n)=>{const k=q.ip+q.path,now=Date.now(),a=(hits.get(k)||[]).filter(t=>now-t<ms);if(a.length>=max)return bad(r,"Too many attempts. Please try again later.",429);a.push(now);hits.set(k,a);n()};
const auth=role=>(req,res,next)=>{try{const u=jwt.verify((req.headers.authorization||"").slice(7),SECRET);if(u.role!==role)return bad(res,"Not allowed",403);req.user=u;next()}catch(e){bad(res,"Please log in again",401)}};
const phoneOk=p=>/^\d{10}$/.test(p||"");
const SEL="SELECT o.*,d.name AS dname FROM orders2 o LEFT JOIN users d ON d.id=o.delivery_id";
const fmt=o=>({id:o.id,cust:o.cust,phone:o.phone,ev:o.ev,cake:o.cake,kg:o.kg,extras:JSON.parse(o.extras||"[]"),date:o.date,slot:o.slot,msg:o.msg,addr:o.addr,total:o.total,pay:o.pay,s:o.s,delivery_id:o.delivery_id,dname:o.dname,created:o.created});
const istDay=()=>new Date(Date.now()+5.5*36e5).toISOString().slice(0,10);
app.get("/",(q,r)=>r.sendFile(__dirname+"/index.html"));
app.get("/healthz",(q,r)=>r.send("ok"));
app.post("/api/login",limit(20,6e5),(req,res)=>{const u=db.prepare("SELECT * FROM users WHERE phone=?").get(String(req.body.phone||""));
 if(!u||!bcrypt.compareSync(String(req.body.password||""),u.pass))return bad(res,"Wrong phone or password.",401);
 res.json({token:jwt.sign({id:u.id,role:u.role,name:u.name},SECRET,{expiresIn:"12h"}),role:u.role,name:u.name})});
app.post("/api/orders",limit(15,36e5),(req,res)=>{const b=req.body||{},name=String(b.name||"").trim().slice(0,60),phone=String(b.phone||""),addr=String(b.addr||"").trim().slice(0,250),msg=String(b.msg||"").slice(0,30);
 const base=CAKES[b.cake],kg=+b.kg,ev=+b.ev;
 if(name.length<2||!phoneOk(phone)||addr.length<10)return bad(res,"Please fill your name, 10-digit phone and full address.");
 if(!base||![0.5,1,2,3].includes(kg)||!Number.isInteger(ev)||ev<0||ev>5||!SLOTS.includes(b.slot))return bad(res,"Invalid booking details.");
 const days=Math.round((Date.parse(String(b.date)+"T00:00:00Z")-Date.parse(istDay()+"T00:00:00Z"))/864e5);
 if(!/^\d{4}-\d{2}-\d{2}$/.test(String(b.date))||isNaN(days)||days<0||days>10)return bad(res,"Event date must be within the next 10 days.");
 let total=Math.round(base*kg);const extras=[],ad=b.ad||{};
 ADDON.forEach((a,i)=>{const q=Math.floor(+ad[i]||0);if(q>=1&&q<=20){total+=a[1]*q;extras.push(q>1?a[0]+" x"+q:a[0])}});
 if(String(b.coupon||"").toUpperCase()==="WISH10")total=Math.round(total*.9);
 const id=(db.prepare("SELECT MAX(id) m FROM orders2").get().m||1000)+1,token=crypto.randomBytes(12).toString("hex"),otp=String(crypto.randomInt(1000,10000));
 db.prepare("INSERT INTO orders2(id,token,cust,phone,ev,cake,kg,extras,date,slot,msg,addr,total,pay,otp,created) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run(id,token,name,phone,ev,b.cake,kg,JSON.stringify(extras),b.date,b.slot,msg,addr,total,"cod",otp,istDay());
 res.json({id,token})});
app.post("/api/orders/track",limit(120,36e5),(req,res)=>{const out=[];(Array.isArray(req.body.ids)?req.body.ids.slice(-30):[]).forEach(x=>{const o=db.prepare(SEL+" WHERE o.id=? AND o.token=?").get(+x.id,String(x.token));if(o)out.push({...fmt(o),otp:o.otp})});res.json(out)});
app.get("/api/admin/orders",auth("admin"),(q,res)=>res.json(db.prepare(SEL+" ORDER BY o.id DESC LIMIT 300").all().map(fmt)));
app.patch("/api/admin/orders/:id",auth("admin"),(req,res)=>{const o=db.prepare("SELECT * FROM orders2 WHERE id=?").get(req.params.id);if(!o||o.s>=3)return bad(res,"Cannot change this order.");
 const dv=req.body.delivery_id||o.delivery_id;if(o.s+1===3&&!dv)return bad(res,"Assign a delivery partner first.");
 db.prepare("UPDATE orders2 SET s=s+1,delivery_id=? WHERE id=?").run(dv||null,o.id);res.json({ok:1})});
app.patch("/api/admin/orders/:id/assign",auth("admin"),(req,res)=>{const d=db.prepare("SELECT id FROM users WHERE id=? AND role='delivery'").get(+req.body.delivery_id);if(!d)return bad(res,"Delivery partner not found.");
 db.prepare("UPDATE orders2 SET delivery_id=? WHERE id=? AND s<4").run(d.id,req.params.id);res.json({ok:1})});
app.get("/api/admin/delivery",auth("admin"),(q,res)=>res.json(db.prepare("SELECT id,name,phone FROM users WHERE role='delivery' ORDER BY name").all()));
app.post("/api/admin/delivery",auth("admin"),(req,res)=>{const{name,phone,password}=req.body||{};if(!String(name||"").trim()||!phoneOk(phone)||String(password||"").length<6)return bad(res,"Enter name, 10-digit mobile and a password of 6+ characters.");
 try{db.prepare("INSERT INTO users(name,phone,pass,role) VALUES(?,?,?,'delivery')").run(String(name).trim().slice(0,60),phone,bcrypt.hashSync(String(password),10));res.json({ok:1})}catch(e){bad(res,"This mobile number is already registered.")}});
app.get("/api/delivery/orders",auth("delivery"),(req,res)=>res.json(db.prepare(SEL+" WHERE o.delivery_id=? AND o.s>=1 ORDER BY o.id DESC LIMIT 100").all(req.user.id).map(fmt)));
app.post("/api/delivery/orders/:id/deliver",auth("delivery"),limit(40,36e5),(req,res)=>{const o=db.prepare("SELECT * FROM orders2 WHERE id=? AND delivery_id=? AND s=3").get(req.params.id,req.user.id);
 if(!o)return bad(res,"This order is not out for delivery.");if(o.otp!==String((req.body||{}).otp||"").trim())return bad(res,"Wrong OTP. Ask the customer for the 4-digit code.");
 db.prepare("UPDATE orders2 SET s=4 WHERE id=?").run(o.id);res.json({ok:1})});
app.use((e,q,res,n)=>bad(res,"Bad request"));
app.listen(process.env.PORT||3000,()=>console.log("Wishme running on port "+(process.env.PORT||3000)));
